name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:      # Allow manual trigger

jobs:
  Sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add upstream remote using stored secret
          git remote add upstream "${{ secrets.UPSTREAM_REPO_URL }}"

      - name: Fetch latest from upstream
        run: |
          # Fetch latest from upstream
          git fetch upstream --prune

          # Determine default branch
          if git rev-parse --verify upstream/main >/dev/null 2>&1; then
            DEFAULT_BRANCH="main"
          elif git rev-parse --verify upstream/master >/dev/null 2>&1; then
            DEFAULT_BRANCH="master"
          else
            echo "::error::Could not find main or master branch in upstream"
            exit 1
          fi
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Create sync branch and PR
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Generate branch names
          DATE_SUFFIX=$(date +%Y%m%d)
          SYNC_BRANCH="sync/upstream-${DATE_SUFFIX}"
          CONFLICT_BRANCH="sync/upstream-conflicts-${DATE_SUFFIX}"
          
          # Fetch and checkout fork_upstream branch
          git fetch origin fork_upstream
          git checkout -b fork_upstream origin/fork_upstream

          # Try to merge upstream changes
          if ! git merge upstream/$DEFAULT_BRANCH --no-edit; then
            echo "::warning::Merge conflicts detected. Creating conflict resolution PR."
            
            # Get conflict details before aborting the merge
            CONFLICTS=$(git diff --name-only --diff-filter=U)
            STATUS=$(git status -s)
            
            # Abort the merge to get to a clean state
            git merge --abort
            
            # Create a new branch based on fork_upstream for the conflict resolution
            # This ensures the branch has shared history with fork_upstream
            git checkout -b $CONFLICT_BRANCH
            
            # Create directories for comparison
            mkdir -p .sync-compare/upstream
            mkdir -p .sync-compare/fork
            
            # Save upstream files for comparison
            git checkout upstream/$DEFAULT_BRANCH
            for file in $(git ls-files); do
              # Create directory structure if needed
              mkdir -p ".sync-compare/upstream/$(dirname "$file")"
              # Copy the file
              cp "$file" ".sync-compare/upstream/$file" 2>/dev/null || true
            done
            
            # Save fork files for comparison
            git checkout fork_upstream
            for file in $(git ls-files); do
              # Create directory structure if needed
              mkdir -p ".sync-compare/fork/$(dirname "$file")"
              # Copy the file
              cp "$file" ".sync-compare/fork/$file" 2>/dev/null || true
            done
            
            # Check out our conflict branch again
            git checkout $CONFLICT_BRANCH
            
            # Add all the comparison files
            git add .sync-compare
            git commit -m "Add upstream and fork state for conflict resolution"
            
            # List the conflicting files in the commit message
            git commit --allow-empty -m "Conflicts detected in: $CONFLICTS"
            
            # Push the branch with comparison content
            git push origin $CONFLICT_BRANCH
            
            # Create conflict resolution PR
            BODY="Conflicts detected while syncing with upstream.

            ### Conflicts
            \`\`\`
            $STATUS
            \`\`\`

            This PR contains both the upstream and fork versions of files to help with conflict resolution.
            - Upstream files are in the \`.sync-compare/upstream/\` directory
            - Fork files are in the \`.sync-compare/fork/\` directory

            Please resolve these conflicts by comparing the two versions and manually applying the necessary changes to the main files."

            gh pr create \
              --base fork_upstream \
              --head $CONFLICT_BRANCH \
              --title "⚠️ Upstream Sync Conflicts - Manual Resolution Required" \
              --body "$BODY"
            
            # Create conflict resolution issue with more details
            ISSUE_BODY="Merge conflicts were detected while syncing from upstream.

            ### Affected Files
            \`\`\`
            $CONFLICTS
            \`\`\`

            ### Resolution Steps
            1. Check out the conflict resolution PR: ${{ github.server_url }}/${{ github.repository }}/pulls
            2. This PR contains both versions of files in the .sync-compare directory
            3. Use the comparison directory to help resolve the conflicts by hand
            4. Create a new branch from fork_upstream and manually apply your changes
            5. Test the changes thoroughly before merging

            ### Additional Details
            - Branch with comparison files: \`$CONFLICT_BRANCH\`
            - Target branch: \`fork_upstream\`
            - Upstream branch: \`$DEFAULT_BRANCH\`

            @${{ github.repository_owner }}"

            gh issue create \
              --title "🔄 Upstream Sync Conflicts Detected $(date +%Y-%m-%d)" \
              --body "$ISSUE_BODY" \
              --label sync-failed \
              --label needs-resolution
            
            exit 0  # Exit successfully after creating the issue and PR
          fi

          # If we're here, the merge succeeded
          # Create a dedicated branch for the successful merge
          git checkout -b $SYNC_BRANCH
          
          # Check if there are any changes to commit
          if git diff --quiet fork_upstream; then
            echo "No changes to sync from upstream"
            exit 0
          fi

          # Push changes
          git push origin $SYNC_BRANCH

          # Get upstream version for PR description
          UPSTREAM_VERSION=$(git describe --tags --abbrev=0 upstream/$DEFAULT_BRANCH 2>/dev/null || echo "latest")

          # Create PR
          gh pr create \
            --base fork_upstream \
            --head $SYNC_BRANCH \
            --title "⬆️ Sync with upstream $UPSTREAM_VERSION" \
            --body "Automated PR to sync with upstream repository changes."

      - name: Create sync-failed label if it doesn't exist
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh label create sync-failed \
            --description "Issues related to sync failures" \
            --color "d73a4a" || true

      - name: Create issue on failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          ISSUE_BODY="The automated upstream sync workflow failed.

          ### Error Details
          Please check the workflow logs for more information:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          ### Manual Steps Required
          1. Review the error logs
          2. Resolve any conflicts
          3. Re-run the sync workflow

          @${{ github.repository_owner }}"

          gh issue create \
            --title "🔄 Upstream Sync Failed $(date +%Y-%m-%d)" \
            --body "$ISSUE_BODY" \
            --label sync-failed